#!/usr/bin/env python3
from __future__ import annotations


"""Command-line replacement for the original slayer2_dumper C++ utility."""
"""Generated by ChatGPT 5.5 medium thinking via Codex 06/07/26"""


import argparse
import bisect
import sys
from dataclasses import dataclass
from pathlib import Path

from utils import dbg 

ROM_FILE_TABLE = 0x19DF08
SUBFILE_TABLE = 0x19DC3C
LAST_FILE_END = 0x1FF71E
SCENE_COUNT = 0x5A

TYPE_PASS2 = 0x04
TYPE_DIRTY = 0x80

ARGS_TABLE = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 2,
    2, 2, 2, 2, 2, 2, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 1, 1,
    1, 1, 2, 2, 3, 0, 2, 0, 3, 3, 0, 0, 1, 1, 1, 1,
]

DUMP_HACKS = {
    (0x00, 0x3B74), (0x02, 0xDA4), (0x03, 0x1932), (0x04, 0x4CF),
    (0x04, 0x17BA), (0x0A, 0x2303), (0x0C, 0x12C7), (0x0C, 0x325A),
    (0x0D, 0x1FEE), (0x0D, 0x3188), (0x0F, 0x2782), (0x10, 0xE10),
    (0x10, 0x2BBE), (0x11, 0x2091), (0x12, 0x186E), (0x13, 0xCFE),
    (0x13, 0x20F8), (0x14, 0x1F46), (0x14, 0x2DBE), (0x15, 0x10E4),
    (0x15, 0x440B), (0x16, 0x1714), (0x16, 0x2F7B), (0x1B, 0x766),
    (0x1B, 0x1528), (0x1D, 0xB7E), (0x1F, 0x1658), (0x21, 0x13B0),
    (0x21, 0x1E73), (0x21, 0x2935), (0x22, 0x10F4), (0x22, 0x187A),
    (0x22, 0x2A5E), (0x23, 0x752), (0x23, 0x1936), (0x23, 0x209E),
    (0x28, 0x1DF0), (0x28, 0x28FC), (0x29, 0xB02), (0x29, 0x15D6),
    (0x29, 0x1FE2), (0x29, 0x29EE), (0x2A, 0xE44), (0x2A, 0x1B34),
    (0x2A, 0x26BE), (0x2A, 0x2F3C), (0x2B, 0x81A), (0x2B, 0x104A),
    (0x2B, 0x1A88), (0x2B, 0x24AA), (0x2C, 0x9D0), (0x2C, 0x132C),
    (0x2C, 0x20A8), (0x2C, 0x2DB0), (0x2D, 0xA04), (0x2D, 0x13BC),
    (0x2D, 0x1EEE), (0x2D, 0x29D0), (0x33, 0x4D46), (0x38, 0x215A),
    (0x50, 0x13ED), (0x50, 0x2491), (0x50, 0x325B), (0x50, 0x3DF7),
    (0x52, 0x34C), (0x52, 0x1034), (0x55, 0x45A),
}

DUMP_REWRITES = {
    (0x1C, 0xFF0): 0x1849, (0x35, 0x714): 0x8C6,
    (0x35, 0x1541): 0x15C2, (0x35, 0x17FA): 0x1883,
    (0x35, 0x1E67): 0x1E68, (0x35, 0x2FEC): 0x3077,
    (0x35, 0x42CA): 0x4355, (0x3E, 0x13C7): 0x14A9,
    (0x3E, 0x2505): 0x25E7, (0x3F, 0x521): 0x603,
    (0x3F, 0x150F): 0x15F1,
}

ATLAS_HEADER = """#VAR(Table, TABLE)\r\n#ADDTBL("slayer2_table.txt", Table)\r\n#ACTIVETBL(Table)\r\n\r\n#SMA("LINEAR")\r\n#EMBTYPE("MSB16", 16, $2)\r\n\r\n#VAR(MyPtr, CUSTOMPOINTER)\r\n#VAR(PtrTable, POINTERTABLE)\r\n\r\n#CREATEPTR(MyPtr, "MSB32", $0, 32)\r\n#PTRTBL(PtrTable, $200000, 4, MyPtr)\r\n\r\n//---------------------------------------------------------\r\n//---------------------------------------------------------\r\n\r\n#LOADPC( "text//atlas_pc.txt" )\r\n#LOADINDEX( "text//atlas_index.txt" )\r\n#LOADPTRTABLE( PtrTable, "text//atlas_ptrtable.txt" )\r\n\r\n"""

ATLAS_FOOTER = """\r\n#SAVEPC( "text//atlas_pc.txt" )\r\n#SAVEINDEX( "text//atlas_index.txt" )\r\n#SAVEPTRTABLE( PtrTable, "text//atlas_ptrtable.txt" )\r\n"""


def be16(data: bytes, offset: int) -> int:
    return int.from_bytes(data[offset:offset + 2], "big")


def be32(data: bytes, offset: int) -> int:
    return int.from_bytes(data[offset:offset + 4], "big")


def signed16(value: int) -> int:
    return value - 0x10000 if value & 0x8000 else value


class ByteWriter:
    def __init__(self, fp):
        self.fp = fp

    def text(self, value: str) -> None:
        self.fp.write(value.encode("utf-8"))

    def raw(self, value: bytes) -> None:
        self.fp.write(value)


class Table:
    def __init__(self, path: Path):
        self.entries: dict[int, bytes] = {}
        for raw_line in path.read_bytes().splitlines():
            line = raw_line.lstrip(b"\xef\xbb\xbf")
            if b"=" not in line:
                continue
            key, value = line.split(b"=", 1)
            try:
                self.entries[int(key, 16)] = value
            except ValueError:
                pass

    def font(self, writer: ByteWriter, tile: int, code: int, multi: bool = False) -> None:
        value = self.entries.get(tile & 0xFFFF)
        if value:
            writer.raw(value)
        elif multi:
            writer.text(f"<${code >> 8:02X}><${code & 0xFF:02X}>")
        else:
            writer.text(f"<${code & 0xFF:02X}>")

    def code(self, writer: ByteWriter, tile: int, code: int, multi: bool = False) -> None:
        value = self.entries.get(tile & 0xFFFF)
        if value:
            writer.raw(value)
        elif multi and (tile >> 8) in self.entries:
            writer.raw(self.entries[tile >> 8])
            writer.text(f"<${tile & 0xFF:02X}>")
        elif multi:
            writer.text(f"<{code >> 8:02X}><${code & 0xFF:02X}>")
        else:
            writer.text(f"<CODE {code & 0xFF:02X}>")


class BitReader:
    def __init__(self, data: bytes, offset: int = 0):
        self.data = data
        self.pos = offset
        self.barrel = 0
        self.count = 0

    def byte(self) -> int:
        if self.pos >= len(self.data):
            raise EOFError("unexpected end of compressed data")
        value = self.data[self.pos]
        self.pos += 1
        return value

    def bit(self) -> int:
        if not self.count:
            self.barrel = self.byte() | (self.byte() << 8)
            self.count = 16
        value = self.barrel & 1
        self.barrel >>= 1
        self.count -= 1
        return value


class BitWriter:
    """Reproduces the C++ SHIFT_BARREL macro's interleaved bit/data stream."""

    def __init__(self):
        self.output = bytearray()
        self.pending = bytearray()
        self.word = 0
        self.bits = 8
        self.first = True

    def bit(self, value: int) -> None:
        if not self.bits:
            if self.first:
                self.word >>= 8
                self.first = False
                self.output.extend(((self.word >> 8) & 0xFF, self.word & 0xFF))
            else:
                self.output.extend((self.word & 0xFF, (self.word >> 8) & 0xFF))
            self.output.extend(self.pending)
            self.pending.clear()
            self.word = 0
            self.bits = 16
        self.word >>= 1
        self.word |= (value & 1) << 15
        self.bits -= 1

    def byte(self, value: int) -> None:
        self.pending.append(value & 0xFF)

    def finish(self) -> bytes:
        for _ in range(self.bits + 1):
            self.bit(0)
        self.output.extend((0, 0))
        if len(self.output) & 1:
            self.output.append(0)
        return bytes(self.output)


def decode_hybrid(data: bytes, offset: int = 0) -> tuple[bytes, int]:
    reader = BitReader(data, offset)
    output = bytearray()
    while True:
        reader.barrel = (reader.byte() << 8) | reader.byte()
        reader.count = 8
        while True:
            if reader.bit() == 0:
                output.append(reader.byte())
                continue
            if reader.bit() == 0:
                window = reader.byte()
            else:
                window = 0
                for _ in range(5):
                    window = (window << 1) | reader.bit()
                window = (window << 8) | reader.byte()
                if window == 0:
                    break
                if window == 1:
                    extended = reader.bit()
                    run = 0
                    for _ in range(4):
                        run = (run << 1) | reader.bit()
                    if extended:
                        run = (run << 8) | reader.byte()
                    output.extend([reader.byte()] * (run + 0xE))
                    continue
            if reader.bit():
                run = 2
            elif reader.bit():
                run = 3
            elif reader.bit():
                run = 4
            elif reader.bit():
                run = 5
            elif reader.bit() == 0:
                run = reader.byte() + 0xE
            else:
                run = 0
                for _ in range(3):
                    run = (run << 1) | reader.bit()
                run += 6
            if window <= 0 or window > len(output):
                raise ValueError(f"invalid LZ window {window:#x} at compressed offset {reader.pos:#x}")
            for _ in range(run):
                output.append(output[-window])
        if reader.byte() == 0:
            break
    return bytes(output), reader.pos - offset


@dataclass
class Match:
    pos: int
    distance: int
    length: int


def _find_match(data: bytes, positions: list[list[int]], start: int) -> tuple[int, int]:
    best_len = 0
    best_pos = 0
    for candidate in positions[data[start]]:
        if candidate >= start:
            break
        distance = start - candidate
        if distance > 0x1FFF:
            continue
        limit = 0x1000 + 0xD if distance == 1 else 0x100 + 0xD
        length = 0
        while start + length < len(data) and length <= limit and data[start + length] == data[candidate + length]:
            length += 1
        if length >= best_len:
            best_len, best_pos = length, candidate
    return best_len, best_pos


def encode_hybrid(data: bytes) -> bytes:
    if not data:
        writer = BitWriter()
        writer.bit(1)
        writer.bit(1)
        for _ in range(5):
            writer.bit(0)
        return writer.finish()

    positions = [[] for _ in range(256)]
    matches: dict[int, Match] = {}
    start = 0
    while start < len(data):
        positions[data[start]].append(start)
        length, pos = _find_match(data, positions, start)
        if start + 1 < len(data):
            positions[data[start + 1]].append(start + 1)
            future_length, _ = _find_match(data, positions, start + 1)
            positions[data[start + 1]].pop()
            if future_length - length >= 1:
                length = 0
        if length >= 2:
            if start - pos == 1 and length > 0x1000 + 0xD:
                length = 0xFFF
            elif length > 0x100 + 0xD:
                length = 0x10B
            matches[start] = Match(start, start - pos, length)
            for index in range(1, length):
                positions[data[start + index]].append(start + index)
            start += length
        else:
            start += 1

    writer = BitWriter()
    start = 0
    while start < len(data):
        match = matches.get(start)
        if not match:
            writer.bit(0)
            writer.byte(data[start])
            start += 1
            continue
        start += match.length
        writer.bit(1)
        if match.distance == 1 and match.length >= 0xE:
            writer.bit(1)
            for _ in range(5):
                writer.bit(0)
            writer.byte(1)
            run = match.length - 0xE
            if run < 16:
                writer.bit(0)
                for bit in range(3, -1, -1):
                    writer.bit(run >> bit)
            else:
                writer.bit(1)
                for bit in range(11, 7, -1):
                    writer.bit(run >> bit)
                writer.byte(run)
            writer.byte(data[match.pos - 1])
            continue
        if match.distance < 256:
            writer.bit(0)
            writer.byte(match.distance)
        else:
            writer.bit(1)
            for bit in range(12, 7, -1):
                writer.bit(match.distance >> bit)
            writer.byte(match.distance)
        length = match.length
        if length == 2:
            writer.bit(1)
        elif length == 3:
            writer.bit(0); writer.bit(1)
        elif length == 4:
            writer.bit(0); writer.bit(0); writer.bit(1)
        elif length == 5:
            writer.bit(0); writer.bit(0); writer.bit(0); writer.bit(1)
        elif length - 6 < 8:
            writer.bit(0); writer.bit(0); writer.bit(0); writer.bit(0); writer.bit(1)
            for bit in range(2, -1, -1):
                writer.bit((length - 6) >> bit)
        else:
            writer.bit(0); writer.bit(0); writer.bit(0); writer.bit(0); writer.bit(0)
            writer.byte(length - 0xE)
    writer.bit(1)
    writer.bit(1)
    for _ in range(5):
        writer.bit(0)
    return writer.finish()


class ScriptDumper:
    def __init__(self, data: bytes, table: Table, writer: ByteWriter, base_name: str, absolute: bool = False, debug_mode: bool = False, verbose_mode: bool = False):
        self.data = data
        self.table = table
        self.out = writer
        self.base_name = base_name
        self.absolute = absolute
        self.debug_mode = debug_mode
        self.verbose_mode = verbose_mode
        self.ptr_list: list[int] = []
        self.mark = bytearray(len(data) + 1)
        self.embed_count = 0
        self.last_dump = -1
        self.last_code = 0
        self.last_stop = 0
        self.jmp_cond = 0
        self.write_rom = False
        self.write_size = 0
        self.write_start = 0

    def byte(self, pos: int) -> int:
        if pos >= len(self.data):
            raise EOFError(f"script read past end at {pos:#x}")
        return self.data[pos]

    def raw_args(self, pos: int, count: int) -> int:
        for value in self.data[pos:pos + count]:
            self.out.text(f"<${value:02X}>")
        return pos + count

    def add_ptr(self, ptr: int) -> None:
        if 0 <= ptr < len(self.mark):
            self.ptr_list.append(ptr)
            self.mark[ptr] |= TYPE_PASS2

    def scan_hard_pointers(self) -> None:
        pattern = [0x43, 0xFA, None, None, 0x2A, 0x7C, None, None, None, None,
                   0x2C, 0x78, 0x02, 0x00, 0x4E, 0x96]
        pos = 0
        while pos + len(pattern) <= len(self.data):
            if all(want is None or self.data[pos + i] == want for i, want in enumerate(pattern)):
                ptr = pos + 2 + signed16(be16(self.data, pos + 2))
                self.add_ptr(ptr)
                if self.verbose_mode:
                    print(f"{ptr:X}", file=sys.stderr)
                pos += len(pattern)
            else:
                pos += 1

    def dump(self, start: int, file_no: int = 0, sub_base: int = 0, pass_no: int = 0) -> None:
        if pass_no == 0 and not self.absolute and file_no == 0xDF and start == 0x543:
            return
        if not 0 <= start < len(self.data):
            return
        if pass_no == 0:
            if self.mark[start] & TYPE_DIRTY:
                return
            self.mark[start] |= TYPE_DIRTY
            self.last_stop = start
            self.jmp_cond = 0
            self.write_rom = False
            self.write_size = 0
            self.last_dump = start
            self.out.text(f"\r\n//[{start:06X}]\r\n\r\n//")

        pos = start
        while pos < len(self.data):
            exit_at_ptr = pos > start and bool(self.mark[pos] & TYPE_PASS2)
            if not self.absolute and pos > start and (
                (file_no == 0x04 and pos == 0x4CF) or (file_no == 0x1D and pos == 0xB7E)
            ):
                exit_at_ptr = True
            if exit_at_ptr:
                if self.write_rom:
                    self._turn_off(pos, True, file_no, sub_base)
                break

            code = self.byte(pos)
            pos += 1
            self.last_code = code

            if pass_no == 0:
                turns_on = code in (0x02, 0x0B, 0x0E, 0x10, 0x16) or 0x20 <= code <= 0xEB
                ignored = code in (0x01, 0x03, 0x04, 0x05, 0x08, 0x09, 0x0C, 0x13, 0x14,
                                   0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F)
                no_inline = not self.absolute and file_no == 0x35 and pos in (0x1A87, 0x1E31)
                if turns_on and not (self.absolute and start == 0x24A66):
                    if no_inline and self.write_rom:
                        self._turn_off(pos, False, file_no, sub_base)
                    elif not self.write_rom:
                        self._turn_on(pos)
                elif not ignored and self.write_rom:
                    self._turn_off(pos, False, file_no, sub_base)

            if 0x20 <= code < 0x80 or 0xA0 <= code < 0xE0:
                if pass_no == 0 and self.write_rom:
                    self.write_size += 1
                self.table.font(self.out, code, code)
                continue
            if 0x80 <= code < 0xA0 or 0xE0 <= code < 0xEB:
                if pass_no == 0 and self.write_rom:
                    self.write_size += 2
                self.out.raw(bytes((code, self.byte(pos))))
                pos += 1
                continue
            if code == 0x09:
                if pass_no == 0 and self.write_rom:
                    self.write_size += 2
                value = (code << 8) | self.byte(pos)
                pos += 1
                self.table.code(self.out, value, value, True)
                continue
            if pass_no > 0 and code in (0x00, 0x06, 0x07, 0x0A, 0x0D, 0x17):
                break

            if code == 0x10:
                no_inline = not self.absolute and file_no == 0x35 and pos in (0x1A87, 0x1E31)
                if no_inline:
                    self.table.code(self.out, code, code)
                    pos = self.raw_args(pos, 2)
                    continue
                if pass_no == 0 and self.write_rom:
                    self.write_size += 3
                relative = be16(self.data, pos)
                suffix = "" if self.absolute else f" @ {pos - 1:04X}"
                self.out.text("\r\n\r\n//")
                self.table.code(self.out, code, code)
                self.out.text(f"<${relative >> 8:02X}><${relative & 0xFF:02X}>{suffix}\r\n")
                target = pos + signed16(relative)
                pos += 2
                saved = pos
                self.dump(target, file_no if not self.absolute else 0, sub_base, pass_no + 1)
                pos = saved
                if self.last_code in (0x07, 0x0A, 0x0D, 0x17):
                    code = 0x01
                else:
                    continue

            if code == 0x15 and pass_no > 0 and not (file_no == 0xCA and pos == 0x12F4):
                print(f"[DUMP_2] FAIL-SAFE $15 @ {pos - 1:04X}")
                break

            self.table.code(self.out, code, code)
            if pass_no == 0 and self.write_rom:
                self.write_size += 1

            if code == 0x16:
                if pass_no > 0:
                    break
                offsets = []
                for index in range(5):
                    offsets.append(pos + signed16(be16(self.data, pos)))
                    pos += 2
                    self.out.text(f"\r\n#EMBSETREL({self.embed_count + index})")
                self.out.text("\r\n")
                self.table.code(self.out, 0x0F, 0x0F)
                self.out.text(f"\r\n#EMBSETREL({self.embed_count + 5})\r\n")
                saved = pos
                for index, target in enumerate(offsets):
                    self.out.text(f"\r\n#EMBWRITEREL({self.embed_count + index})\r\n")
                    self.dump(target, file_no, sub_base, pass_no + 1)
                    self.table.code(self.out, self.last_code, self.last_code)
                    self.out.text("\r\n")
                self.last_stop = pos
                pos = saved
                self.out.text(f"\r\n#EMBWRITEREL({self.embed_count + 5})\r\n")
                self.embed_count += 6
                continue

            if code in (0x11, 0x12):
                self.jmp_cond = 1
            if code == 0x0F:
                if pass_no > 0:
                    break
                target = pos + signed16(be16(self.data, pos))
                pos = self.raw_args(pos, 2)
                self.out.text("\r\n//")
                self.add_ptr(target)
                if self.jmp_cond:
                    self.jmp_cond = 0
                    continue
                break

            arg_code = code - 0xC0 if code >= 0xEB else code
            count = ARGS_TABLE[arg_code]
            pos = self.raw_args(pos, count)
            if pass_no == 0 and self.write_rom:
                self.write_size += count
            if code in (0x00, 0x06, 0x07, 0x0A, 0x0D, 0x17):
                self.out.text("\r\n//")
                break
            if code in (0x01, 0x03):
                self.out.text("\r\n" if self.write_rom else "\r\n//")
            elif code == 0x05:
                self.out.text("\r\n\r\n" if self.write_rom else "\r\n\r\n//")

        if pass_no == 0:
            self.last_stop = max(self.last_stop, pos)
            if self.absolute:
                self.out.text(f"\r\n\r\n//[TEXT] {start:06X}-{self.last_stop:06X}")
            else:
                self.out.text(
                    f"\r\n\r\n//[TEXT] {start:06X}-{self.last_stop:06X} "
                    f"[{0x6650 + start - sub_base:06X}-{0x6650 + self.last_stop - sub_base:06X}]"
                )
            self.out.text("\r\n//////////////////////////////////////////////////////////\r\n\r\n")
            if self.verbose_mode:
                print(f"[TEXT] {start:06X}-{self.last_stop:06X}")
            next_pos = DUMP_REWRITES.get((file_no, pos), pos)
            if (file_no, pos) in DUMP_HACKS or next_pos != pos:
                self.add_ptr(next_pos)

    def _turn_on(self, pos: int) -> None:
        self.write_rom = True
        self.write_size = 0
        self.write_start = pos + 2
        if self.absolute:
            self.out.text(f"\r\n\r\n#WRITE(PtrTable)\r\n#W08BYTE(${pos - 1:X}, $EB)\r\n#WRITEINDEX(${pos:X}, 2)\r\n\r\n")
        else:
            self.out.text(
                f'\r\n\r\n#WRITE(PtrTable)\r\n#W08BYTE(${pos - 1:X}, $EB, "insert/{self.base_name}")'
                f'\r\n#WRITEINDEX(${pos:X}, 2, "insert/{self.base_name}")\r\n\r\n'
            )

    def _turn_off(self, pos: int, exit_at_ptr: bool, file_no: int, sub_base: int) -> None:
        self.write_rom = False
        end = pos if exit_at_ptr else pos - 1
        if not self.absolute and file_no == 0x55 and pos == 0x45A:
            self.write_size = 3
        target = end if self.absolute else end + 0x6650 - sub_base
        if self.absolute:
            jump = f"<${target >> 24 & 0xFF:02X}><${target >> 16 & 0xFF:02X}><${target >> 8 & 0xFF:02X}><${target & 0xFF:02X}>"
            fill = f"#FILL(${self.write_start:X}, ${end:X}, $00)"
        else:
            if self.debug_mode:            
                dbg(f"{self.write_start:X} {end:X}",exit_at_ptr)  
            if exit_at_ptr:
                end -= 1
            jump = f"<$FF><$FF><${target >> 8 & 0xFF:02X}><${target & 0xFF:02X}>"
            fill = f'#FILL(${self.write_start:X}, ${end:X}, $00, "insert//{self.base_name}")'
        self.out.text(f"\r\n\r\n<JMP.L>{jump}\r\n{fill}\r\n")
        if self.write_size < 3:
            self.out.text(f"\r\n//[WARN] INDEX WRITE_SIZE = {self.write_size}")
            print(f"[WARN] INDEX WRITE_SIZE = {self.write_size}")
        self.out.text("\r\n//")


def read_subfile_lengths(rom: bytes) -> list[list[int]]:
    result = []
    pos = SUBFILE_TABLE
    for _ in range(SCENE_COUNT):
        lengths = [be16(rom, pos + index * 2) for index in range(4)]
        pos += 8
        cumulative = [0]
        cumulative.append(lengths[0])
        cumulative.append(lengths[0] + lengths[1])
        cumulative.append(lengths[0] + lengths[1] + lengths[2])
        result.append(cumulative)
    return result


def scene_range(value: str) -> tuple[int, int]:
    parts = value.split("-", 1)
    start = int(parts[0], 16)
    stop = int(parts[-1], 16)
    if not (0 <= start <= stop < SCENE_COUNT):
        raise argparse.ArgumentTypeError("scene range must be between 00 and 59")
    return start, stop


def dump_file(args) -> None:
    rom = args.rom.read_bytes()
    table = Table(args.table)
    subfiles = read_subfile_lengths(rom)
    args.binary_dir.mkdir(parents=True, exist_ok=True)
    args.text_dir.mkdir(parents=True, exist_ok=True)
    start, stop = args.scenes
    for scene in range(start, stop + 1):
        ptr = ROM_FILE_TABLE + be32(rom, ROM_FILE_TABLE + scene * 4)
        decoded, consumed = decode_hybrid(rom, ptr + 2)
        base_name = f"{scene:02X}_{ptr:X}.bin"
        binary_path = args.binary_dir / base_name
        binary_path.write_bytes(decoded)
        if args.verbose:
            print(f"[DECODE] {binary_path} ({consumed:#x} compressed bytes)", file=sys.stderr)
        text_path = args.text_dir / f"script_{scene:02X}.txt"
        debug_mode = False
        #if "script_35.txt" in str(text_path):   
        #    debug_mode = True                   
        #else:                                   
        #    debug_mode = False                  

        with text_path.open("wb") as fp:
            binary_path_str = str(args.binary_dir)+"//"+str(base_name)   # duplicate the formatting found in dumper.cpp line 124
            writer = ByteWriter(fp)
            writer.text(ATLAS_HEADER)
            writer.text(f"\r\n//////////////////////////////////////////////////////////\r\n//********************************************************\r\n//[FILE] {binary_path_str}\r\n\r\n")
            dumper = ScriptDumper(decoded, table, writer, base_name,debug_mode=debug_mode,verbose_mode=args.verbose)
            dumper.scan_hard_pointers()
            while dumper.ptr_list:
                target = min(dumper.ptr_list)
                dumper.ptr_list.remove(target)
                sub_base = subfiles[scene][bisect.bisect_right(subfiles[scene], target) - 1]
                dumper.dump(target, scene, sub_base)
            writer.text(ATLAS_FOOTER)


def insert_file(args) -> None:
    rom = bytearray(args.rom.read_bytes())
    start, stop = args.scenes
    for scene in range(start, stop + 1):
        ptr = ROM_FILE_TABLE + be32(rom, ROM_FILE_TABLE + scene * 4)
        file_end = LAST_FILE_END if scene == SCENE_COUNT - 1 else ROM_FILE_TABLE + be32(rom, ROM_FILE_TABLE + (scene + 1) * 4)
        path = args.insert_dir / f"{scene:02X}_{ptr:X}.bin"
        encoded = encode_hybrid(path.read_bytes())
        begin = ptr + 2
        rom[begin:begin + len(encoded)] = encoded
        print(f"[FILE {scene:02X}] {begin:X}-{begin + len(encoded):X} [{file_end:X}]")
        if begin + len(encoded) > file_end:
            print(f"OVERWRITE = {begin + len(encoded) - file_end:X} bytes")
    args.output.write_bytes(rom)


def dump_strings(args) -> None:
    rom = args.rom.read_bytes()
    table = Table(args.table)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("wb") as fp:        
        writer = ByteWriter(fp)
        writer.text(ATLAS_HEADER)
        dumper = ScriptDumper(rom, table, writer, args.rom.name, absolute=True)
        for line in args.pointer_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith(";"):
                dumper.add_ptr(int(line, 16))
        while dumper.ptr_list:
            target = min(dumper.ptr_list)
            dumper.ptr_list.remove(target)
            dumper.dump(target, -1)
            writer.text("\r\n#EMBCLEAR()\r\n")
        writer.text(ATLAS_FOOTER)


def command_decode(args) -> None:
    decoded, consumed = decode_hybrid(args.input.read_bytes(), args.offset)
    args.output.write_bytes(decoded)
    print(f"decoded {len(decoded):#x} bytes from {consumed:#x} compressed bytes")


def command_encode(args) -> None:
    encoded = encode_hybrid(args.input.read_bytes())
    args.output.write_bytes(encoded)
    print(f"encoded {args.input.stat().st_size:#x} bytes to {len(encoded):#x} bytes")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    dump = sub.add_parser("dump-file", help="decompress scenes and generate Atlas scripts")
    dump.add_argument("rom", type=Path)
    dump.add_argument("--scenes", type=scene_range, default=(0, SCENE_COUNT - 1), metavar="START-STOP")
    dump.add_argument("--table", type=Path, default=Path("table/table_main_8x14.txt"))
    dump.add_argument("--binary-dir", type=Path, default=Path("binary"))
    dump.add_argument("--text-dir", type=Path, default=Path("text"))
    dump.add_argument("--verbose",action="store_true")
    dump.set_defaults(func=dump_file)

    insert = sub.add_parser("insert-file", help="compress scene files into a copy of the ROM")
    insert.add_argument("rom", type=Path)
    insert.add_argument("scenes", type=scene_range, metavar="START-STOP")
    insert.add_argument("--insert-dir", type=Path, default=Path("insert"))
    insert.add_argument("-o", "--output", type=Path, required=True, help="output ROM (the input is never modified)")
    insert.add_argument("--verbose",action="store_true")
    insert.set_defaults(func=insert_file)

    strings = sub.add_parser("dump-strings", help="dump absolute ROM strings listed in a pointer file")
    strings.add_argument("rom", type=Path)
    strings.add_argument("--pointer-file", type=Path, default=Path("text/dump_strings.txt"))
    strings.add_argument("--table", type=Path, default=Path("table/table_main_8x14.txt"))
    strings.add_argument("-o", "--output", type=Path, default=Path("text/strings.txt"))
    strings.add_argument("--verbose",action="store_true")
    strings.set_defaults(func=dump_strings)

    decode = sub.add_parser("decode", help="decompress one hybrid-LZ stream")
    decode.add_argument("input", type=Path)
    decode.add_argument("output", type=Path)
    decode.add_argument("--offset", type=lambda value: int(value, 0), default=0)
    decode.add_argument("--verbose",action="store_true")
    decode.set_defaults(func=command_decode)

    encode = sub.add_parser("encode", help="compress one file as a hybrid-LZ stream")
    encode.add_argument("input", type=Path)
    encode.add_argument("output", type=Path)
    encode.add_argument("--verbose",action="store_true")
    encode.set_defaults(func=command_encode)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    try:
        args.func(args)
    except (EOFError, FileNotFoundError, ValueError) as error:
        dbg(error)
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
